version: '3.8'

services:
  redis:
    image: redis:6.2

  django:
    build:
      context: ./django
    entrypoint: /bin/bash /app/entrypoint.sh
    volumes:
      - "./django/src:/app"
    depends_on:
      - redis

  djangochanels:
    build:
      context: ./django
    entrypoint: /bin/bash /app/entrypoint_chanels.sh
    volumes:
      - "./django/src:/app"
    depends_on:
      - redis

  nginx:
    image: nginx:1.20
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - django
      - djangochanels
