version: '3.8'

services:
  redis:
    image: redis:6.2

  django:
    build:
      context: ./django
    entrypoint: /bin/bash /app/src/entrypoint.sh
    volumes:
      - "./django:/app"
    ports:
      - "8000:8000"
    depends_on:
      - redis
